---
abstract: 'Fast, high-quality fixed-point image resizing'
author:
  - 'Andy Grundman <andy@hybridized.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Image-Scale
no_index:
  directory:
    - t
    - inc
requires:
  Test::NoWarnings: '0'
  perl: '5.008'
resources:
  repository: https://github.com/andygrundman/Image-Scale.git
version: '0.13'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
